### ISSUE TITLE
hello, fish shell now supports new options `fish_color_option`, is there a plan to support this?

### ISSUE THREAD

**Issue by zzhaolei** [mienaikage/fish-theme-dracula#16]
Related [docs](https://fishshell.com/docs/3.4/interactive.html?highlight=fish_color_option)

**Comment by jaminthorns** [comment]
Thank you for letting us know about this! I just pushed up d00be76c79486334efa90ed1831d8bc8087acd54, which adds `fish_color_option` and a few other things.

**Comment by zzhaolei** [comment]
It's amazing.
