### ISSUE TITLE
Maintenance of this Repository

### ISSUE THREAD

**Issue by jaminthorns** [mienaikage/fish-theme-dracula#9]
It seems that this repository isn't being actively maintained. There are 2 small PRs by @Trollwut that I think are reasonable which have no feedback after 2 months. I have tried to get in contact with @mienaikage with no luck. Nothing wrong with this, of course, people get busy and whatnot.

@zenorocha I would be glad to help out with this theme if you'd like to make me a contributor. I've been using the Dracula theme for years, and am actively using this `fish` one (well, actually @Trollwut's fork).

Thanks!

**Comment by Trollwut** [comment]
hey, I'm also using @Trollwut's fork :D 

very nice to hear I could help someone out with my little adjustments.

Just wanted to say that I would also volunteer to take this repo, if needed. Not wanting to take it from @jaminthorns of course, he's numero uno :)

**Comment by zenorocha** [comment]
Added you both to the list of maintainers https://github.com/dracula/fish/commit/0ed2f47a18465e45b178f64c1404e12a8b5f0186!

I'm really excited. This fish theme definitely needs some love and I'm sure you'll both be able to provide it.

Should we start with the screenshot? :)
